### ISSUE TITLE
Not found error - Undefined symbol - Image ops

### ISSUE THREAD

**Issue by pabloduque0** [tensorflow/addons#2289]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): (pip) tensorflow==2.2.0
- TensorFlow-Addons version and how it was installed (source or binary): (pip) tensorflow-addons==0.11.2
- Python version: 3.6.9
- Is GPU used? (yes/no): No (but tried on GPU and same error)

**Describe the bug**

The following error is raised when training a model that uses tfa.image.connected_components in one of the metrics:

    NotFoundError: /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesESt16initializer_listIN4absl14lts_2020_02_2511string_viewEE

I can run the function (metric) by itself isolated but not when training a network.

**Code to reproduce the issue**

Code is raised when using tfa.image.connected_components. For example when calculating a object wise recall (for segmentation):

```
def lession_recall(y_true, y_pred):
    conn_comp_true = tfa.image.connected_components(tf.cast(tf.squeeze(y_true, axis=[-1]), tf.bool))
    conn_comp_pred = conn_comp_true * tf.cast(tf.squeeze(y_pred, axis=[-1]), tf.int32)
​
    n_conn_comp_true, _ = tf.unique(backend.flatten(conn_comp_true))
    n_conn_comp_pred, _ = tf.unique(backend.flatten(conn_comp_pred))
    n_conn_comp_true = tf.size(input=n_conn_comp_true) - 1
    n_conn_comp_pred = tf.size(input=n_conn_comp_pred) - 1
​
    recall = tf.cond(pred=tf.equal(n_conn_comp_true, tf.Variable(0)),
                     true_fn=lambda: tf.Variable(1.0, dtype=tf.float64), false_fn=lambda: n_conn_comp_pred / n_conn_comp_true)
    return recall
```

**Other info / logs**

Full log:

```
Traceback (most recent call last):
  File "src/train/trainer.py", line 80, in <module>
    os.path.abspath(args.models_path))
  File "src/train/trainer.py", line 64, in main
    full_training_name, models_path, epochs=40, batch_size=15)
  File "/home/pduque/phd/wmh_segmentation/src/models/basenetwork.py", line 164, in train
    verbose=1)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/comet_ml/monkey_patching.py", line 292, in wrapper
    return_value = original(*args, **kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 627, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 506, in _initialize
    *args, **kwds))
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2446, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2777, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2667, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 981, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 441, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.NotFoundError: in user code:
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow_addons/image/connected_components.py:70 connected_components  *
        components = _image_so.ops.addons_image_connected_components(images)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow_addons/utils/resource_loader.py:64 ops
        self._ops = tf.load_op_library(get_path_to_datafile(self.relative_path))
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py:58 load_op_library
        lib_handle = py_tf.TF_LoadLibrary(library_filename)
    NotFoundError: /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow_addons/custom_ops/image/_image_ops.so: undefined symbol: _ZN10tensorflow7strings8internal9CatPiecesESt16initializer_listIN4absl14lts_2020_02_2511string_viewEE
```

**Comment by bhack** [comment]
Are you running this from your source dir?

**Comment by bhack** [comment]
If you are running this inside your source directory you could check https://github.com/tensorflow/addons/pull/1909.

But It Is still not merged.

**Comment by pabloduque0** [comment]
@bhack I see that #1909 is for running it with docker which is not the case here.

**Comment by bhack** [comment]
It is for Docker and generally in source run.

**Comment by pabloduque0** [comment]
Both TFA and TF were installed by binary (with pip). I believe is not a source run what I am doing. Would still be related to #1909 ? Any other ideas?

**Comment by bhack** [comment]
No that PR Is only related for in source runs.
Can you try with Tensorflow 2.3.1?

**Comment by pabloduque0** [comment]
For tensorflow 2.3.1:

First I get the warning for TFA-TF compatibility
```
UserWarning: You are currently using TensorFlow 2.3.1 and trying to load a custom op (custom_ops/image/_image_ops.so).
TensorFlow Addons has compiled its custom ops against TensorFlow 2.2.0, and there are no compatibility guarantees between the two versions. 
This means that you might get segfaults when loading the custom op, or other kind of low-level errors.
 If you do, do not file an issue on Github. This is a known limitation.

It might help you to fallback to pure Python ops with TF_ADDONS_PY_OPS . To do that, see https://github.com/tensorflow/addons#gpucpu-custom-ops 

You can also change the TensorFlow version installed on your system. You would need a TensorFlow version equal to or above 2.2.0 and strictly below 2.3.0.
 Note that nightly versions of TensorFlow, as well as non-pip TensorFlow like `conda install tensorflow` or compiled from source are not supported.

The last solution is to find the TensorFlow Addons version that has custom ops compatible with the TensorFlow installed on your system. To do that, refer to the readme: https://github.com/tensorflow/addons

```

And the error is the following: 

```
    ValueError: tf.function-decorated function tried to create variables on non-first call.

```

Full log:

```
Traceback (most recent call last):
  File "src/train/trainer.py", line 80, in <module>
    os.path.abspath(args.models_path))
  File "src/train/trainer.py", line 64, in main
    full_training_name, models_path, epochs=40, batch_size=15)
  File "/home/pduque/phd/wmh_segmentation/src/models/basenetwork.py", line 164, in train
    verbose=1)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/comet_ml/monkey_patching.py", line 292, in wrapper
    return_value = original(*args, **kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1098, in fit
    tmp_logs = train_function(iterator)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2828, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:806 train_function  *
        return step_function(self, iterator)
    /home/pduque/phd/wmh_segmentation/src/models/metrics.py:77 custom_dice_f1_loss  *
        return -custom_dice_f1(y_true, y_pred)
    /home/pduque/phd/wmh_segmentation/src/models/metrics.py:16 custom_dice_f1  *
        f1_weight = tf.Variable(f1_weight, dtype=tf.float32)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:262 __call__  **
        return cls._variable_v2_call(*args, **kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:256 _variable_v2_call
        shape=shape)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2857 creator
        return next_creator(**kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2857 creator
        return next_creator(**kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2857 creator
        return next_creator(**kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/ops/variables.py:67 getter
        return captured_getter(captured_previous, **kwargs)
    /home/pduque/phd/wmh_segmentation/venv_remote/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py:702 invalid_creator_scope
        "tf.function-decorated function tried to create "

    ValueError: tf.function-decorated function tried to create variables on non-first call.

```

**Comment by bhack** [comment]
Yes for the first warning Is not a problem cause It Is Just 2.3.1 vs 2.3.0 that Is a security fix.

Instead is the second error related to your code.

**Comment by pabloduque0** [comment]
Totally right! I miss that one, sorry.

Thank you very much, I'll close this one.

**Comment by petered** [comment]
Not sure if this is at al related to the original poster's problem, but I got the same error (and came to this thread looking to solve it).  In the end, it was easily solved it by downgrading to a version of TensorFlow_addons (0.16.1), that was compiled against my TensorFlow version (2.8.1).  With 

```
pip uninstall tensorflow-addons
pip install tensorflow-addons==0.16.1
```
