### ISSUE TITLE
ResourceVariable object has no attribute update_op

### ISSUE THREAD

**Issue by hongyan19890126** [tensorflow/addons#2510]
It looks like it can't compute gradients when I using tfra.dynamic_embedding.embedding_lookup,

Errors below:

Traceback (most recent call last):
  File "./main.py", line 224, in <module>
    max_eval_steps=5)
  File "./main.py", line 111, in train_eval
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 505, in train_and_evaluate
    return executor.run()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 646, in run
    return self.run_local()
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/training.py", line 747, in run_local
    saving_listeners=saving_listeners)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default
    self.config)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "./main.py", line 116, in model_fn
    return model.build_graph(mode, config)
  File "/home/oneflow/wdl_tensorflow/wdl_dynamic.py", line 342, in build_graph
    train_op = self.build_train_ops(loss)
  File "/home/oneflow/wdl_tensorflow/wdl_dynamic.py", line 385, in build_train_ops
    train_op = d_optimizer.apply_gradients(grads_and_vars, global_step=global_step)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 616, in apply_gradients
    update_ops.append(processor.update_op(self, grad))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py", line 80, in update_op
    [_s.update_op() for _s in _slots])
  File "/opt/conda/lib/python3.6/site-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py", line 80, in <listcomp>
    [_s.update_op() for _s in _slots])
AttributeError: 'ResourceVariable' object has no attribute 'update_op'

Can anyone solve this problem?

**Comment by fsx950223** [comment]
Open it in https://github.com/tensorflow/recommenders-addons
