### ISSUE TITLE
Nadam with MovingAverage or SWA throws error "no attribute '_m_cache_read'"

### ISSUE THREAD

**Issue by YinSun0** [tensorflow/addons#2662]
**System information**
- Linux Ubuntu 18.04
- TensorFlow version 2.7.0 (with pip install)
- TensorFlow-Addons version 0.15.0
- Python version 3.6 + Ipython version 7.22
- Is GPU used? No.

**Describe the bug**

In any and every regular Neural Network I try (that is, I did not try CNNs, GNNs or RNNs) to use MovingAverage or SWA with the Nadam optimizer, I get an error.

**Code to reproduce the issue**

After loading required libraries:

```
from tensorflow import keras as ks
import tensorflow_addons as tfa
```

If I then try to `fit()` a mode with the:

```
optimizer = ks.optimizers.Nadam()
optimizer = tfa.optimizers.MovingAverage(optimizer)
```

or

```
optimizer = ks.optimizers.Nadam()
optimizer = tfa.optimizers.SWA(optimizer)
```

I get a error stating:

> AttributeError: 'Nadam' object has no attribute '_m_cache_read'

The detailed output:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-821-76be14036ebf> in <module>
> ----> 1 fitted = model.fit(trainX, trainY, epochs=nEpochs)
> 
> ~/anaconda3/lib/python3.8/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
>      65     except Exception as e:  # pylint: disable=broad-except
>      66       filtered_tb = _process_traceback_frames(e.__traceback__)
> ---> 67       raise e.with_traceback(filtered_tb) from None
>      68     finally:
>      69       del filtered_tb
> 
> ~/anaconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*a
> rgs, **kwargs)
>    1127           except Exception as e:  # pylint:disable=broad-except
>    1128             if hasattr(e, "ag_error_metadata"):
> -> 1129               raise e.ag_error_metadata.to_exception(e)
>    1130             else:
>    1131               raise
> 
> AttributeError: in user code:
> 
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 878, in tr
> ain_function  *
>         return step_function(self, iterator)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 867, in st
> ep_function  **
>         outputs = model.distribute_strategy.run(run_step, args=(data,))
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 860, in ru
> n_step  **
>         outputs = model.train_step(data)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/engine/training.py", line 816, in tr
> ain_step
>         self.optimizer.minimize(loss, self.trainable_variables, tape=tape)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 
> 532, in minimize
>         return self.apply_gradients(grads_and_vars, name=name)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/tensorflow_addons/optimizers/average_wrapp
> er.py", line 56, in apply_gradients
>         return super().apply_gradients(grads_and_vars, name, **kwargs)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 
> 665, in apply_gradients
>         apply_state = self._prepare(var_list)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 
> 949, in _prepare
>         self._prepare_local(var_device, var_dtype, apply_state)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/tensorflow_addons/optimizers/average_wrapp
> er.py", line 52, in _prepare_local
>         return self._optimizer._prepare_local(var_device, var_dtype, apply_state)
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/optimizer_v2/nadam.py", line 114, in
>  _prepare_local
>         m_schedule_new = tf.cast(self._m_cache_read, var_dtype) * m_t
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 
> 845, in __getattribute__
>         raise e
>     File "/home/yinsun/anaconda3/lib/python3.8/site-packages/keras/optimizer_v2/optimizer_v2.py", line 
> 835, in __getattribute__
>         return super(OptimizerV2, self).__getattribute__(name)
> 
>     AttributeError: 'Nadam' object has no attribute '_m_cache_read'

**Comment by sky2code** [comment]
me too, the same problem

**Comment by sky2code** [comment]
the  tensorflow 2.8.0 has release, when tensorflow-addons 0.16.0 release?
