### ISSUE TITLE
Bazel build fails when trying to download llvm

### ISSUE THREAD

**Issue by atuleu** [tensorflow/addons#2730]
**System information**
- Pop_OS 22.04
- Not installed
- Not installed (source build)
- Python version: 3.8.12
- Is GPU used? (yes/no): yes

**Describe the bug**
While trying a source build from master, bazelisk cannot get llvm-raw from github
**Code to reproduce the issue**
```bash
git clone https://github.com/tensorflow/addons.git
cd addons

export TF_NEED_CUDA=1
python3 configure.py

bazelisk build build_pip_pkg.sh
```

**Other info / logs**

The above would produce:
```
Starting local Bazel server and connecting to it...
INFO: Repository llvm-raw instantiated at:
  /data/atuleu/addons/WORKSPACE:33:14: in <toplevel>
  /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/org_tensorflow/tensorflow/workspace3.bzl:42:9: in workspace
  /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/org_tensorflow/third_party/llvm/workspace.bzl:10:20: in repo
  /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/org_tensorflow/third_party/repo.bzl:128:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/org_tensorflow/third_party/repo.bzl:81:35: in <toplevel>
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
WARNING: Download from https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz failed: class java.io.IOException Read timed out
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
	File "/home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/org_tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/llvm-raw/temp2642465594096602227/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/org_tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
		ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/llvm-raw/temp2642465594096602227/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
ERROR: no such package '@llvm-raw//utils/bazel': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz, https://github.com/llvm/llvm-project/archive/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz] to /home/atuleu/.cache/bazel/_bazel_atuleu/54737f76a285434a5718a654185b57b2/external/llvm-raw/temp2642465594096602227/1cb299165c859533e22f2ed05eb2abd5071544df.tar.gz: Read timed out
INFO: Elapsed time: 164.355s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

```

**Comment by seanpmorgan** [comment]
TensorFlow Addons is transitioning to a minimal maintenance and release mode. New features will not be added to this repository. For more information, please see our public messaging on this decision:
[TensorFlow Addons Wind Down](https://github.com/tensorflow/addons/issues/2807)

Please consider sending feature requests / contributions to other repositories in the TF community with a similar charters to TFA:
[Keras](https://github.com/keras-team/keras)
[Keras-CV](https://github.com/keras-team/keras-cv)
[Keras-NLP](https://github.com/keras-team/keras-nlp)
