### ISSUE TITLE
Tensorflow-models-official call problem

### ISSUE THREAD

**Issue by zhengjoe** [tensorflow/addons#2827]
import tensorflow_models as tfm
C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_models\__init__.py", line 17, in <module>
    from tensorflow_models import nlp
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_models\nlp\__init__.py", line 17, in <module>
    from official.nlp import tasks
  File "C:\Users\lenovo\anaconda3\lib\site-packages\official\nlp\tasks\__init__.py", line 17, in <module>
    from official.nlp.tasks.electra_task import ElectraPretrainConfig, ElectraPretrainTask
  File "C:\Users\lenovo\anaconda3\lib\site-packages\official\nlp\tasks\electra_task.py", line 20, in <module>
    from official.core import base_task
  File "C:\Users\lenovo\anaconda3\lib\site-packages\official\core\__init__.py", line 23, in <module>
    from official.core import input_reader
  File "C:\Users\lenovo\anaconda3\lib\site-packages\official\core\input_reader.py", line 21, in <module>
    import tensorflow_datasets as tfds
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\__init__.py", line 43, in <module>
    import tensorflow_datasets.core.logging as _tfds_logging
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\__init__.py", line 22, in <module>
    from tensorflow_datasets.core import community
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\community\__init__.py", line 18, in <module>
    from tensorflow_datasets.core.community.huggingface_wrapper import mock_builtin_to_use_gfile
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\community\huggingface_wrapper.py", line 31, in <module>
    from tensorflow_datasets.core import dataset_builder
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in <module>
    from tensorflow_datasets.core import dataset_info
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in <module>
    from tensorflow_datasets.core import file_adapters
  File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in <module>
    from array_record.python import array_record_module
ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\Users\lenovo\anaconda3\lib\site-packages\array_record\python\__init__.py)

**Comment by seanpmorgan** [comment]
This is not an TFA issue:
```
File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_builder.py", line 34, in
from tensorflow_datasets.core import dataset_info
File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\dataset_info.py", line 47, in
from tensorflow_datasets.core import file_adapters
File "C:\Users\lenovo\anaconda3\lib\site-packages\tensorflow_datasets\core\file_adapters.py", line 29, in
from array_record.python import array_record_module
ImportError: cannot import name 'array_record_module' from 'array_record.python' (C:\Users\lenovo\anaconda3\lib\site-packages\array_record\python_init_.py)
```

The warning you see printed above the error is unrelated to your ImportError
