### ISSUE TITLE
testBadParentValuesOnGPU failed on GPU 

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#348]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-gpu-2.0-preview
- TensorFlow Addons installed from (source, PyPi): source
- TensorFlow Addons version: master
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): tensorflow/tensorflow:custom-op-gpu
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):
- Is GPU used? (yes/no): yes
- GPU model (if used):

**Describe the bug**

testBadParentValuesOnGPU failed on GPU.

```python
ERROR: testBadParentValuesOnGPU (__main__.GatherTreeTest)
testBadParentValuesOnGPU (__main__.GatherTreeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 37, in testPartExecutor
    yield
  File "/usr/local/lib/python2.7/dist-packages/absl/third_party/unittest3_backport/case.py", line 162, in run
    testMethod()
  File "/root/.cache/bazel/_bazel_root/e051f2f195071208ea7f081f88730f4f/execroot/__main__/bazel-out/k8-opt/bin/tensorflow_addons/seq2seq/beam_search_ops_test.runfiles/__main__/tensorflow_addons/seq2seq/beam_search_ops_test.py", line 93, in testBadParentValuesOnGPU
    end_token=end_token)
  File "<string>", line 69, in gather_tree
  File "<string>", line 126, in gather_tree_eager_fallback
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 737, in raise_from
    raise value
InvalidArgumentError: Saw invalid parent id -1 at (batch, time, beam) == (0, 0, 1) [Op:GatherTree]
```

**Describe the expected behavior**

**Code to reproduce the issue**

**Other info / logs**

https://source.cloud.google.com/results/invocations/dc386dab-6aeb-4fed-bf01-cc4b8e65c43e/targets/tensorflow_addons%2Fubuntu%2Fgpu%2Fpy2%2Fpresubmit/log

**Comment by facaiy** [comment]
The bug is found when working on https://github.com/tensorflow/addons/pull/294
