### ISSUE TITLE
TQDMProgressBar: Cannot register a class that does not have a get_config() method.

### ISSUE THREAD

**Issue by Squadrick** [tensorflow/addons#679]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): 2.1.0-dev20191029
- TensorFlow-Addons version and how it was installed (source or binary): `master`
- Python version: 3.6.8
- Is GPU used? (yes/no): no

**Describe the bug**

`TQDMProgressBar` doesn't implement `get_config()`.

**Code to reproduce the issue**

Fails on import:
```
import tensorflow_addons as tfa
```

**Other info / logs**
```
>>> import tensorflow_addons as tfa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/squadrick/.local/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 22, in <module>
    from tensorflow_addons import callbacks
  File "/home/squadrick/.local/lib/python3.6/site-packages/tensorflow_addons/callbacks/__init__.py", line 21, in <module>
    from tensorflow_addons.callbacks.tqdm_progress_bar import TQDMProgressBar
  File "/home/squadrick/.local/lib/python3.6/site-packages/tensorflow_addons/callbacks/tqdm_progress_bar.py", line 27, in <module>
    class TQDMProgressBar(Callback):
  File "/home/squadrick/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 165, in decorator
    'Cannot register a class that does not have a get_config() method.')
ValueError: Cannot register a class that does not have a get_config() method.
```

Google Colab [Link](https://colab.research.google.com/drive/15awUrrTMY_NsqVoE0OwS7N3sl9nd3V2W).

**Comment by Squadrick** [comment]
cc @shun-lin

**Comment by shun-lin** [comment]
@Squadrick got it, will update as soon as I can :)
