### ISSUE TITLE
dense_image_warp error

### ISSUE THREAD

**Issue by kevinkingo** [tensorflow/addons#711]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary): 2.0.0, Binary
- TensorFlow-Addons version and how it was installed (source or binary): 0.6.0, Binary
- Python version: 3.7.4
- Is GPU used? (yes/no): yes

**Describe the bug**
tfa.image.dense_image_warp is not compatible with TF 2.0 keras model

**Code to reproduce the issue**

```
import cv2
import numpy as np
import tensorflow as tf
from tensorflow import keras
import tensorflow_addons as tfa

x = keras.Input(shape=(None, None, 3))
offset = keras.Input(shape=(None, None, 2))
out = tfa.image.dense_image_warp(x, offset)
net = keras.Model(inputs=[x, offset], outputs=out)
```

**Other info / logs**
```

Traceback (most recent call last):
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 61, in quick_execute
    num_outputs)
TypeError: An op outside of the function building code is being passed
a "Graph" tensor. It is possible to have Graph tensors
leak out of the function building context by including a
tf.init_scope in your function building code.
For example, the following function will fail:
  @tf.function
  def has_init_scope():
    my_constant = tf.constant(1.)
    with tf.init_scope():
      added = my_constant * 2
The graph tensor has name: input_1:0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kingo/Documents/test.py", line 9, in <module>
    out = tfa.image.dense_image_warp(x, offset)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 526, in _call
    return self._concrete_stateful_fn._filtered_call(canon_args, canon_kwds)  # pylint: disable=protected-access
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/kingo/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 75, in quick_execute
    "tensors, but found {}".format(keras_symbolic_tensors))
tensorflow.python.eager.core._SymbolicException: Inputs to eager execution function cannot be Keras symbolic tensors, but found [<tf.Tensor 'input_1:0' shape=(None, None, None, 3) dtype=float32>, <tf.Tensor 'input_2:0' shape=(None, None, None, 2) dtype=float32>]
[Finished in 6.4s]

```

**Comment by WindQAQ** [comment]
Because `dense_image_warp` is decorated with `tf.function`, you have to wrap it with `tf.keras.layers.Lambda`. Here is a workable [notebook](https://colab.research.google.com/drive/1UdFmBkevENDVdEKoZFl5l6zjTUa5qL8x). Please let me you if you have further questions. Thank you.

**Comment by seanpmorgan** [comment]
Closing. Please feel free to re-open if there are additional questions.
